import { requireString } from "../../../../packages/contracts/src/common/index.mjs";
import { parseBrowseNavigateInput, parseBrowseOpenInput } from "../../../../packages/contracts/src/browse/index.mjs";
import { createErrorResponse, ERROR_CODES } from "../../../../packages/contracts/src/errors/index.mjs";
import { parseTabInput } from "../../../../packages/contracts/src/tabs/index.mjs";
import { assertUrlAllowed } from "../../../../packages/policy/src/index.mjs";
import { jsonResponse, readJsonBody } from "../common/http.mjs";
import { derivePageTitle, getRecord, withRoute, writeAudit, writeRecord } from "../common/service-helpers.mjs";

const RELAY_USER_AGENT = "OpenSkyRelay/1.0";
const DEMO_ORIGIN_HOST = "demo.opensky.local";
const FORWARDED_REQUEST_HEADERS = new Set([
  "accept",
  "accept-language",
  "accept-encoding",
  "cache-control",
  "content-type",
  "if-none-match",
  "if-modified-since",
  "range",
  "x-requested-with",
  "x-csrf-token",
  "x-xsrf-token"
]);
const BLOCKED_RESPONSE_HEADERS = new Set([
  "connection",
  "content-encoding",
  "content-length",
  "content-security-policy",
  "content-security-policy-report-only",
  "set-cookie",
  "set-cookie2",
  "transfer-encoding",
  "x-frame-options"
]);

function shouldIncludeRequestBody(method = "GET") {
  const normalizedMethod = String(method).toUpperCase();
  return normalizedMethod !== "GET" && normalizedMethod !== "HEAD";
}

function createRelayRequestHeaders(incomingHeaders, cookieHeader) {
  const headers = {
    "user-agent": RELAY_USER_AGENT
  };
  const normalizedIncomingHeaders = incomingHeaders instanceof Headers
    ? incomingHeaders
    : new Headers(incomingHeaders ?? {});

  for (const [headerName, headerValue] of normalizedIncomingHeaders.entries()) {
    const normalizedHeaderName = String(headerName).toLowerCase();
    if (!FORWARDED_REQUEST_HEADERS.has(normalizedHeaderName)) {
      continue;
    }
    headers[normalizedHeaderName] = headerValue;
  }

  if (cookieHeader) {
    headers.cookie = cookieHeader;
  }

  return headers;
}

function toProxyResponseHeaders(response) {
  const headers = {};
  response.headers.forEach((value, key) => {
    const normalizedKey = String(key).toLowerCase();
    if (BLOCKED_RESPONSE_HEADERS.has(normalizedKey)) {
      return;
    }
    headers[normalizedKey] = value;
  });
  if (!headers["cache-control"]) {
    headers["cache-control"] = "private, max-age=60";
  }
  return headers;
}

function createDemoOriginResponse(targetUrl) {
  const parsedUrl = new URL(targetUrl);
  const pathname = parsedUrl.pathname || "/";

  if (pathname === "/" || pathname === "/index.html") {
    return new Response(`<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title>OpenSky Demo Origin</title>
    <link rel="stylesheet" href="/assets/demo.css" />
  </head>
  <body>
    <main class="demo-shell">
      <p class="demo-eyebrow">OpenSky verified preset</p>
      <h1>OpenSky Demo Origin</h1>
      <p class="demo-copy">This page is generated by the backend demo origin so the controlled relay can render it completely and predictably.</p>
      <div class="demo-actions">
        <a href="/status">Status</a>
        <a href="/guide">Guide</a>
      </div>
      <img src="/assets/opensky-demo.svg" alt="OpenSky demo badge" width="360" height="160" />
    </main>
  </body>
</html>`, {
      status: 200,
      headers: {
        "content-type": "text/html; charset=utf-8"
      }
    });
  }

  if (pathname === "/status") {
    return new Response(`<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>OpenSky Demo Status</title>
    <link rel="stylesheet" href="/assets/demo.css" />
  </head>
  <body>
    <main class="demo-shell">
      <p class="demo-eyebrow">Controlled relay status</p>
      <h1>Demo Status Page</h1>
      <p class="demo-copy">The current preset supports full document rendering, same-domain CSS, SVG assets, and controlled navigation.</p>
      <a href="/">Back to demo home</a>
    </main>
  </body>
</html>`, {
      status: 200,
      headers: {
        "content-type": "text/html; charset=utf-8"
      }
    });
  }

  if (pathname === "/guide") {
    return new Response(`<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>OpenSky Demo Guide</title>
    <link rel="stylesheet" href="/assets/demo.css" />
  </head>
  <body>
    <main class="demo-shell">
      <p class="demo-eyebrow">How to test</p>
      <h1>Demo Guide</h1>
      <ol class="demo-steps">
        <li>Select the seeded demo site.</li>
        <li>Use the seeded demo project.</li>
        <li>Open the controlled page.</li>
        <li>Navigate between the demo links.</li>
      </ol>
      <a href="/">Back to demo home</a>
    </main>
  </body>
</html>`, {
      status: 200,
      headers: {
        "content-type": "text/html; charset=utf-8"
      }
    });
  }

  if (pathname === "/assets/demo.css") {
    return new Response(`
      :root {
        color-scheme: light;
        --demo-bg: #eef6ff;
        --demo-card: #ffffff;
        --demo-ink: #102a43;
        --demo-accent: #2f7cf6;
        --demo-border: #bfd7ff;
      }

      body {
        margin: 0;
        min-height: 100vh;
        font-family: "Segoe UI", Tahoma, sans-serif;
        background:
          radial-gradient(circle at top, rgba(47, 124, 246, 0.14), transparent 40%),
          linear-gradient(180deg, #f8fbff 0%, var(--demo-bg) 100%);
        color: var(--demo-ink);
      }

      .demo-shell {
        width: min(820px, calc(100% - 48px));
        margin: 40px auto;
        padding: 28px;
        border: 1px solid var(--demo-border);
        border-radius: 28px;
        background: rgba(255, 255, 255, 0.96);
        box-shadow: 0 24px 60px rgba(16, 42, 67, 0.12);
      }

      .demo-eyebrow {
        margin: 0 0 10px;
        text-transform: uppercase;
        letter-spacing: 0.12em;
        font-size: 12px;
        font-weight: 700;
        color: var(--demo-accent);
      }

      h1 {
        margin: 0 0 12px;
        font-size: clamp(2rem, 4vw, 3rem);
      }

      .demo-copy,
      .demo-steps {
        font-size: 1rem;
        line-height: 1.7;
      }

      .demo-actions {
        display: flex;
        gap: 12px;
        flex-wrap: wrap;
        margin: 22px 0;
      }

      a {
        color: var(--demo-accent);
      }

      .demo-actions a {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        padding: 10px 14px;
        border: 1px solid var(--demo-border);
        border-radius: 999px;
        background: #fff;
        text-decoration: none;
        font-weight: 600;
      }

      img {
        display: block;
        max-width: 100%;
        height: auto;
        margin-top: 20px;
      }
    `, {
      status: 200,
      headers: {
        "content-type": "text/css; charset=utf-8"
      }
    });
  }

  if (pathname === "/assets/opensky-demo.svg") {
    return new Response(`<svg xmlns="http://www.w3.org/2000/svg" width="360" height="160" viewBox="0 0 360 160" role="img" aria-label="OpenSky demo badge">
  <defs>
    <linearGradient id="bg" x1="0" x2="1" y1="0" y2="1">
      <stop offset="0%" stop-color="#2f7cf6"/>
      <stop offset="100%" stop-color="#7cc4ff"/>
    </linearGradient>
  </defs>
  <rect width="360" height="160" rx="28" fill="url(#bg)"/>
  <circle cx="76" cy="80" r="34" fill="rgba(255,255,255,0.2)"/>
  <circle cx="112" cy="58" r="22" fill="rgba(255,255,255,0.35)"/>
  <text x="152" y="70" font-family="Segoe UI, Tahoma, sans-serif" font-size="20" font-weight="700" fill="#ffffff">OpenSky Demo</text>
  <text x="152" y="98" font-family="Segoe UI, Tahoma, sans-serif" font-size="14" fill="#eaf5ff">Verified local relay preset</text>
</svg>`, {
      status: 200,
      headers: {
        "content-type": "image/svg+xml; charset=utf-8"
      }
    });
  }

  return new Response("Demo origin resource not found.", {
    status: 404,
    headers: {
      "content-type": "text/plain; charset=utf-8"
    }
  });
}

function matchAllowedDomain(candidateUrl, site) {
  const hostname = new URL(candidateUrl).hostname.toLowerCase();
  return (site.baseDomains ?? []).some((domain) => {
    const normalizedDomain = String(domain ?? "").trim().toLowerCase();
    return hostname === normalizedDomain || hostname.endsWith(`.${normalizedDomain}`);
  });
}

function assertResourceUrlAllowed(candidateUrl, site, traceId) {
  if (!matchAllowedDomain(candidateUrl, site)) {
    throw createErrorResponse(
      ERROR_CODES.RESOURCE_DOMAIN_NOT_ALLOWED,
      "This page depends on assets that are outside the current allowlisted site domains.",
      "Add the required asset domains to the site allowlist, or treat this site as partially supported.",
      traceId
    );
  }
}

function createProxyResourceUrl(tabId, resourceUrl) {
  return `/v1/browse/resource?tabId=${encodeURIComponent(tabId)}&resourceUrl=${encodeURIComponent(resourceUrl)}`;
}

function rewriteCssContent(cssText, baseUrl, tabId) {
  const rewriteUrl = (value) => {
    const trimmed = String(value ?? "").trim().replace(/^['"]|['"]$/gu, "");
    if (!trimmed || trimmed.startsWith("data:") || trimmed.startsWith("javascript:")) {
      return trimmed;
    }

    try {
      const resolvedUrl = new URL(trimmed, baseUrl).href;
      return createProxyResourceUrl(tabId, resolvedUrl);
    } catch {
      return trimmed;
    }
  };

  return String(cssText ?? "")
    .replace(/url\(([^)]+)\)/giu, (_, value) => `url("${rewriteUrl(value)}")`)
    .replace(/@import\s+(?:url\()?["']?([^"')\s]+)["']?\)?/giu, (_, value) => `@import url("${rewriteUrl(value)}")`);
}

function collectUnsupportedResourceHosts(documentHtml, baseUrl, site) {
  const hosts = new Set();
  const html = String(documentHtml ?? "");
  const cssPattern = /url\(([^)]+)\)|@import\s+(?:url\()?["']?([^"')\s]+)["']?\)?/giu;

  const tryAddUrl = (candidate) => {
    const trimmed = String(candidate ?? "").trim().replace(/^['"]|['"]$/gu, "");
    if (!trimmed || trimmed.startsWith("data:") || trimmed.startsWith("javascript:") || trimmed.startsWith("#")) {
      return;
    }

    try {
      const absoluteUrl = new URL(trimmed, baseUrl).href;
      if (!matchAllowedDomain(absoluteUrl, site)) {
        hosts.add(new URL(absoluteUrl).hostname.toLowerCase());
      }
    } catch {
      // Ignore malformed upstream URLs.
    }
  };

  const resourceTagPatterns = [
    /<script\b[^>]*\bsrc\s*=\s*["']([^"']+)["'][^>]*>/giu,
    /<img\b[^>]*\bsrc\s*=\s*["']([^"']+)["'][^>]*>/giu,
    /<img\b[^>]*\bsrcset\s*=\s*["']([^"']+)["'][^>]*>/giu,
    /<source\b[^>]*\bsrc\s*=\s*["']([^"']+)["'][^>]*>/giu,
    /<source\b[^>]*\bsrcset\s*=\s*["']([^"']+)["'][^>]*>/giu,
    /<video\b[^>]*\bposter\s*=\s*["']([^"']+)["'][^>]*>/giu,
    /<link\b[^>]*\brel\s*=\s*["'][^"']*(?:stylesheet|preload|modulepreload|icon|apple-touch-icon|mask-icon|manifest)[^"']*["'][^>]*\bhref\s*=\s*["']([^"']+)["'][^>]*>/giu,
    /<link\b[^>]*\bhref\s*=\s*["']([^"']+)["'][^>]*\brel\s*=\s*["'][^"']*(?:stylesheet|preload|modulepreload|icon|apple-touch-icon|mask-icon|manifest)[^"']*["'][^>]*>/giu
  ];

  for (const pattern of resourceTagPatterns) {
    for (const match of html.matchAll(pattern)) {
      if (!match[1]) {
        continue;
      }
      if (/srcset/iu.test(pattern.source)) {
        for (const entry of match[1].split(",")) {
          const [candidateUrl] = entry.trim().split(/\s+/, 1);
          tryAddUrl(candidateUrl);
        }
        continue;
      }
      tryAddUrl(match[1]);
    }
  }

  for (const match of html.matchAll(cssPattern)) {
    tryAddUrl(match[1] ?? match[2]);
  }

  return [...hosts].sort();
}

async function fetchRelayResponse(
  currentUrl,
  site,
  context,
  traceId,
  scope = "browse-relay",
  scopeRef = { siteId: site.siteId, projectId: null },
  requestOptions = {}
) {
  if (new URL(currentUrl).hostname.toLowerCase() === DEMO_ORIGIN_HOST) {
    return createDemoOriginResponse(currentUrl);
  }

  const method = String(requestOptions.method ?? "GET").toUpperCase();
  const requestBody = shouldIncludeRequestBody(method) ? requestOptions.body : undefined;
  const cookieHeader = await context.relayCookieJar?.getCookieHeader?.(scopeRef, currentUrl);
  const requestHeaders = createRelayRequestHeaders(requestOptions.headers, cookieHeader);
  const fetchOptions = {
    method,
    redirect: requestOptions.redirect ?? "follow",
    headers: requestHeaders
  };
  if (requestBody !== undefined) {
    fetchOptions.body = requestBody;
    fetchOptions.duplex = "half";
  }

  const response = await context.fetch(currentUrl, fetchOptions).catch(async (error) => {
    await context.logger?.write?.({
      level: "error",
      scope,
      siteId: site.siteId,
      currentUrl,
      message: `Relay fetch failed: ${error.message}`
    }).catch(() => undefined);
    throw createErrorResponse(
      ERROR_CODES.SERVICE_UNAVAILABLE,
      "OpenSky could not retrieve the requested allowlisted page.",
      "Retry in a moment. If the issue persists, inspect the backend log.",
      traceId
    );
  });

  await context.relayCookieJar?.capture?.(scopeRef, currentUrl, response, { persist: true }).catch(async (error) => {
    await context.logger?.write?.({
      level: "warning",
      scope: "relay-cookie-capture",
      siteId: scopeRef.siteId,
      projectId: scopeRef.projectId,
      currentUrl,
      message: `Failed to capture upstream cookies: ${error.message}`
    }).catch(() => undefined);
  });

  return response;
}

async function fetchRelayDocument(currentUrl, tabId, site, projectId, context, traceId) {
  const response = await fetchRelayResponse(
    currentUrl,
    site,
    context,
    traceId,
    "browse-relay",
    {
      siteId: site.siteId,
      projectId: projectId ?? null
    },
    {
      method: "GET",
      headers: {
        accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
      }
    }
  );
  const finalUrl = response.url || currentUrl;
  assertUrlAllowed(finalUrl, site, traceId);

  const contentType = String(response.headers.get("content-type") ?? "text/html");
  const body = await response.text();
  const unsupportedHosts = collectUnsupportedResourceHosts(body, finalUrl, site);

  if (unsupportedHosts.length) {
    await context.logger?.write?.({
      level: "warning",
      scope: "browse-content",
      siteId: site.siteId,
      currentUrl,
      finalUrl,
      unsupportedHosts,
      message: `Proxy Phase 1 detected cross-domain assets outside the allowlist: ${unsupportedHosts.join(", ")}`
    }).catch(() => undefined);
  }

  return {
    finalUrl,
    contentType,
    documentHtml: body,
    scriptCount: (body.match(/<script\b/giu) ?? []).length,
    renderMode: "allowlist-proxy-phase1",
    resourceBaseUrl: createProxyResourceUrl(tabId, finalUrl),
    unsupportedHosts
  };
}

export function registerBrowseRoutes(router) {
  router.add("POST", "/v1/browse/open", withRoute(async ({ request, context, traceId, actor }) => {
    const payload = parseBrowseOpenInput(await readJsonBody(request));
    const site = await getRecord(context, "sites", payload.siteId, ERROR_CODES.SITE_NOT_FOUND, traceId, "Site");
    const project = await getRecord(context, "projects", payload.projectId, ERROR_CODES.PROJECT_NOT_FOUND, traceId, "Project");

    if (site.status !== "active") {
      throw createErrorResponse(ERROR_CODES.SITE_DISABLED, "This site is not active.", "Choose an active allowlisted site.", traceId);
    }

    assertUrlAllowed(payload.entryUrl, site, traceId);
    const tabId = await context.store.nextId("tab");
    const tab = {
      tabId,
      ...parseTabInput({
        projectId: project.projectId,
        siteId: site.siteId,
        entryUrl: payload.entryUrl,
        currentUrl: payload.entryUrl,
        pageTitle: derivePageTitle(payload.entryUrl, site.displayName),
        renderMode: site.defaultRenderMode ?? "allowlist-proxy-phase1",
        status: "open"
      })
    };
    await writeRecord(context, "tabs", tabId, tab);
    await writeRecord(context, "projects", project.projectId, {
      ...project,
      status: project.status === "draft" ? "active" : project.status,
      lastOpenedAt: new Date().toISOString()
    });
    await writeAudit(context, { actorId: actor.actorId, action: "browse.open", targetType: "WorkspaceTab", targetId: tabId, result: "success" });
    return jsonResponse(tab, { status: 201 });
  }));

  router.add("POST", "/v1/browse/navigate", withRoute(async ({ request, context, traceId, actor }) => {
    const payload = parseBrowseNavigateInput(await readJsonBody(request));
    const tab = await getRecord(context, "tabs", payload.tabId, ERROR_CODES.TAB_NOT_FOUND, traceId, "Tab");
    const site = await getRecord(context, "sites", tab.siteId, ERROR_CODES.SITE_NOT_FOUND, traceId, "Site");
    assertUrlAllowed(payload.nextUrl, site, traceId);

    const updatedTab = {
      ...tab,
      currentUrl: payload.nextUrl,
      pageTitle: derivePageTitle(payload.nextUrl, site.displayName),
      status: "open",
      lastVisitedAt: new Date().toISOString()
    };
    await writeRecord(context, "tabs", tab.tabId, updatedTab);
    await writeAudit(context, { actorId: actor.actorId, action: "browse.navigate", targetType: "WorkspaceTab", targetId: tab.tabId, result: "success" });
    return jsonResponse(updatedTab);
  }));

  router.add("POST", "/v1/browse/close", withRoute(async ({ request, context, traceId, actor }) => {
    const payload = await readJsonBody(request);
    const tab = await getRecord(context, "tabs", payload.tabId, ERROR_CODES.TAB_NOT_FOUND, traceId, "Tab");
    const updatedTab = { ...tab, status: "closed", lastVisitedAt: new Date().toISOString() };
    await writeRecord(context, "tabs", payload.tabId, updatedTab);
    await writeAudit(context, { actorId: actor.actorId, action: "browse.close", targetType: "WorkspaceTab", targetId: payload.tabId, result: "success" });
    return jsonResponse(updatedTab);
  }));

  router.add("GET", "/v1/browse/content", withRoute(async ({ context, url, traceId, actor }) => {
    const tabId = requireString(url.searchParams.get("tabId"), "tabId");
    const tab = await getRecord(context, "tabs", tabId, ERROR_CODES.TAB_NOT_FOUND, traceId, "Tab");
    const site = await getRecord(context, "sites", tab.siteId, ERROR_CODES.SITE_NOT_FOUND, traceId, "Site");
    assertUrlAllowed(tab.currentUrl, site, traceId);

    const relay = await fetchRelayDocument(tab.currentUrl, tab.tabId, site, tab.projectId ?? null, context, traceId);
    const nextPageTitle = derivePageTitle(relay.finalUrl, site.displayName);
    const updatedTab = relay.finalUrl !== tab.currentUrl || nextPageTitle !== tab.pageTitle
      ? {
          ...tab,
          currentUrl: relay.finalUrl,
          pageTitle: nextPageTitle,
          lastVisitedAt: new Date().toISOString()
        }
      : tab;

    if (updatedTab !== tab) {
      await writeRecord(context, "tabs", tab.tabId, updatedTab);
    }

    await writeAudit(context, {
      actorId: actor.actorId,
      action: "browse.content",
      targetType: "WorkspaceTab",
      targetId: tab.tabId,
      result: "success"
    });

    return jsonResponse({
      tabId: tab.tabId,
      requestedUrl: tab.currentUrl,
      finalUrl: relay.finalUrl,
      pageTitle: updatedTab.pageTitle,
      contentType: relay.contentType,
      documentHtml: relay.documentHtml,
      scriptCount: relay.scriptCount,
      renderMode: relay.renderMode,
      resourceBaseUrl: relay.resourceBaseUrl,
      unsupportedHosts: relay.unsupportedHosts,
      warningMessage: relay.unsupportedHosts.length
        ? `This site loads assets from additional domains (${relay.unsupportedHosts.join(", ")}). Add those domains to the allowlist if you need a closer proxy match.`
        : null
    });
  }));

  const proxyResourceMethods = ["GET", "HEAD", "POST", "PUT", "PATCH", "DELETE"];
  for (const method of proxyResourceMethods) {
    router.add(method, "/v1/browse/resource", withRoute(async ({ request, context, url, traceId }) => {
      const tabId = requireString(url.searchParams.get("tabId"), "tabId");
      const resourceUrl = requireString(url.searchParams.get("resourceUrl"), "resourceUrl");
      const tab = await getRecord(context, "tabs", tabId, ERROR_CODES.TAB_NOT_FOUND, traceId, "Tab");
      const site = await getRecord(context, "sites", tab.siteId, ERROR_CODES.SITE_NOT_FOUND, traceId, "Site");
      const requestMethod = String(request.method ?? "GET").toUpperCase();
      const requestBody = shouldIncludeRequestBody(requestMethod)
        ? await request.arrayBuffer()
        : undefined;

      assertResourceUrlAllowed(resourceUrl, site, traceId);
      const response = await fetchRelayResponse(
        resourceUrl,
        site,
        context,
        traceId,
        "browse-resource",
        {
          siteId: site.siteId,
          projectId: tab.projectId ?? null
        },
        {
          method: requestMethod,
          headers: request.headers,
          body: requestBody && requestBody.byteLength > 0 ? requestBody : undefined
        }
      );
      const finalUrl = response.url || resourceUrl;
      assertResourceUrlAllowed(finalUrl, site, traceId);

      const contentType = String(response.headers.get("content-type") ?? "application/octet-stream");
      const baseHeaders = {
        ...toProxyResponseHeaders(response),
        "content-type": contentType,
        "x-opensky-relay-url": finalUrl
      };

      if (requestMethod === "HEAD") {
        return new Response(null, {
          status: response.status,
          headers: baseHeaders
        });
      }

      if (contentType.includes("text/css")) {
        const cssText = await response.text();
        const rewrittenCss = rewriteCssContent(cssText, finalUrl, tab.tabId);
        return new Response(rewrittenCss, {
          status: response.status,
          headers: baseHeaders
        });
      }

      return new Response(await response.arrayBuffer(), {
        status: response.status,
        headers: baseHeaders
      });
    }));
  }
}
