export const ERROR_CODES = Object.freeze({
  AUTH_REQUIRED: "AUTH_REQUIRED",
  FORBIDDEN: "FORBIDDEN",
  SITE_NOT_FOUND: "SITE_NOT_FOUND",
  SITE_DISABLED: "SITE_DISABLED",
  URL_NOT_ALLOWED: "URL_NOT_ALLOWED",
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  TAB_NOT_FOUND: "TAB_NOT_FOUND",
  BOOKMARK_NOT_FOUND: "BOOKMARK_NOT_FOUND",
  NOTE_NOT_FOUND: "NOTE_NOT_FOUND",
  SESSION_VAULT_NOT_FOUND: "SESSION_VAULT_NOT_FOUND",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  LOGIN_PERSISTENCE_DISABLED: "LOGIN_PERSISTENCE_DISABLED",
  UPLOAD_PREVIEW_REQUIRED: "UPLOAD_PREVIEW_REQUIRED",
  FILE_TYPE_NOT_ALLOWED: "FILE_TYPE_NOT_ALLOWED",
  DOWNLOAD_DISABLED: "DOWNLOAD_DISABLED",
  UPLOAD_DISABLED: "UPLOAD_DISABLED",
  CONFLICT_RETRY: "CONFLICT_RETRY",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  INVALID_INPUT: "INVALID_INPUT",
  FULLSCREEN_NOT_AVAILABLE: "FULLSCREEN_NOT_AVAILABLE"
});

export function createErrorResponse(code, message, userAction, traceId) {
  return {
    code,
    message,
    userAction,
    traceId
  };
}
